# .github/workflows/deploy.yaml
name: Deploy Landing Page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the Vite app
      - name: Build site
        run: npm run build

      # Step 5: Deploy to server via rsync
      - name: Deploy to server
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz --delete
          path: dist/
          remote_path: /var/www/html/
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_KEY }}

